onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
patchedDependencies:
  '@tiptap/core@3.31.4': patches/@tiptap__core@3.31.4.patch
  '@tiptap/y-tiptap@3.0.9': patches/@tiptap__y-tiptap@3.0.9.patch
