-- Narrative Layer (pgvector)
-- Stores prose/narrative chunks with embeddings for semantic search
-- Links to ontology primitives and entities via IDs for Neo4j sync

SET search_path TO elt, public;

-- Enable pgvector extension for embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- NARRATIVE CHUNKS
-- ============================================================================

CREATE TABLE IF NOT EXISTS narrative_chunks (
    -- Identity
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Narrative content
    narrative_text TEXT NOT NULL,              -- The prose/story generated by agent
    narrative_type TEXT NOT NULL,              -- 'action', 'event', 'day', 'week', 'chapter', 'telos'

    -- Temporal context
    time_start TIMESTAMPTZ NOT NULL,           -- When this narrative begins
    time_end TIMESTAMPTZ NOT NULL,             -- When this narrative ends
    time_granularity TEXT NOT NULL,            -- 'minute', 'hour', 'day', 'week', 'month', 'year'

    -- Hierarchy references (for pgvector queries)
    parent_narrative_id UUID REFERENCES narrative_chunks(id) ON DELETE CASCADE,
    child_narrative_ids UUID[],                -- Denormalized for convenience

    -- Ontology primitive references (what this narrative is about)
    -- JSONB format: {"health_heart_rate": ["uuid1", "uuid2"], "social_email": ["uuid3"]}
    ontology_primitive_ids JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Entity references (split by type for Neo4j sync)
    person_ids UUID[],                         -- References entities_person
    place_ids UUID[],                          -- References entities_place
    topic_ids UUID[],                          -- References entities_topic

    -- Semantic search
    embedding vector(1536),                    -- OpenAI ada-002 or similar (1536 dimensions)

    -- Metadata
    token_count INTEGER,                       -- Length in tokens
    confidence_score FLOAT CHECK (confidence_score >= 0 AND confidence_score <= 1),
    generation_model TEXT,                     -- Which LLM generated this (e.g., 'claude-3-5-sonnet-20241022')

    -- Agent attribution
    generated_by TEXT NOT NULL DEFAULT 'narrative_agent_v1',
    generation_prompt_version TEXT,            -- Track prompt versions for reproducibility

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CHECK (time_end > time_start),
    CHECK (narrative_type IN ('action', 'event', 'day', 'week', 'chapter', 'telos'))
);

-- ============================================================================
-- ESSENTIAL INDEXES (MVP)
-- ============================================================================

-- Time-based queries (ESSENTIAL for "show me last week")
CREATE INDEX idx_narrative_time_range
    ON narrative_chunks(time_start, time_end);

-- Hierarchy traversal (ESSENTIAL for "show parent day")
CREATE INDEX idx_narrative_parent
    ON narrative_chunks(parent_narrative_id)
    WHERE parent_narrative_id IS NOT NULL;

-- Type filtering (ESSENTIAL for "show all events")
CREATE INDEX idx_narrative_type
    ON narrative_chunks(narrative_type);

-- Entity array lookups (ESSENTIAL for "all events with Sarah")
CREATE INDEX idx_narrative_people
    ON narrative_chunks USING GIN (person_ids);

CREATE INDEX idx_narrative_places
    ON narrative_chunks USING GIN (place_ids);

CREATE INDEX idx_narrative_topics
    ON narrative_chunks USING GIN (topic_ids);

-- Ontology primitive lookups (ESSENTIAL for "find narrative for this email")
CREATE INDEX idx_narrative_primitives
    ON narrative_chunks USING GIN (ontology_primitive_ids jsonb_path_ops);

-- ============================================================================
-- DEFERRED INDEXES (Add after MVP when you have data)
-- ============================================================================

-- Vector similarity search (IVFFlat index - requires data to tune 'lists' parameter)
-- Uncomment after you have 10k+ narrative chunks and know your query patterns:
-- CREATE INDEX idx_narrative_embedding
--     ON narrative_chunks USING ivfflat (embedding vector_cosine_ops)
--     WITH (lists = 100);

-- Full-text search (uncomment if semantic search isn't sufficient)
-- CREATE INDEX idx_narrative_search
--     ON narrative_chunks USING GIN (to_tsvector('english', narrative_text));

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE TRIGGER narrative_chunks_updated_at
    BEFORE UPDATE ON narrative_chunks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE narrative_chunks IS 'Narrative prose chunks with embeddings for semantic search. Generated by agent from ontology primitives. Synced to Neo4j for hierarchical structure.';

COMMENT ON COLUMN narrative_chunks.narrative_text IS 'The actual narrative/story text (prose) generated by the narrative agent';
COMMENT ON COLUMN narrative_chunks.narrative_type IS 'Hierarchy level: action (minutes), event (hours), day, week, chapter (months), telos (years/life arc)';
COMMENT ON COLUMN narrative_chunks.time_granularity IS 'Temporal resolution of this narrative chunk';
COMMENT ON COLUMN narrative_chunks.parent_narrative_id IS 'Parent in hierarchy (e.g., event parent is day, day parent is week)';
COMMENT ON COLUMN narrative_chunks.child_narrative_ids IS 'Denormalized array of child narrative IDs for quick access';
COMMENT ON COLUMN narrative_chunks.ontology_primitive_ids IS 'JSONB map of primitive table name to array of UUIDs (e.g., {"social_email": ["uuid1"], "health_heart_rate": ["uuid2", "uuid3"]})';
COMMENT ON COLUMN narrative_chunks.person_ids IS 'Array of entities_person UUIDs involved in this narrative';
COMMENT ON COLUMN narrative_chunks.place_ids IS 'Array of entities_place UUIDs where this narrative occurred';
COMMENT ON COLUMN narrative_chunks.topic_ids IS 'Array of entities_topic UUIDs this narrative relates to';
COMMENT ON COLUMN narrative_chunks.embedding IS 'Vector embedding (1536d) for semantic similarity search';
COMMENT ON COLUMN narrative_chunks.confidence_score IS 'Agent confidence in narrative quality (0.0-1.0)';
COMMENT ON COLUMN narrative_chunks.generation_model IS 'LLM model used to generate this narrative (for reproducibility and debugging)';
COMMENT ON COLUMN narrative_chunks.generation_prompt_version IS 'Prompt template version for reproducibility';
