-- Narrative Primitive Table
-- Represents the fundamental "scenes" of a person's day using the 6 W's framework.
-- Generated by the unified narrative primitive pipeline (entity resolution → changepoint detection → synthesis).
--
-- Design Philosophy: Hybrid Link + Snapshot
-- - Foreign keys for graph traversal (place_id, participant_ids)
-- - JSONB snapshots for fast LLM synthesis without expensive JOINs
-- - Avoids "time travel" bugs where historical narratives break when entities change

CREATE TABLE IF NOT EXISTS data.narrative_primitive (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- ==========================================
    -- 1. WHEN (The Temporal Container)
    -- ==========================================
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    duration_seconds INTEGER GENERATED ALWAYS AS
        (EXTRACT(EPOCH FROM (end_time - start_time))) STORED,

    -- ==========================================
    -- 2. WHERE (The Stage)
    -- ==========================================
    -- Structural Link
    place_id UUID REFERENCES data.entities_place(id),
    -- Context Snapshot (Fast read for LLM without joining)
    place_label TEXT,          -- e.g., "Home", "Virtues HQ"
    is_transit BOOLEAN DEFAULT FALSE,

    -- ==========================================
    -- 3. WHO (The Cast)
    -- ==========================================
    -- Structural Links
    participant_ids UUID[] DEFAULT '{}', -- Links to data.entities_person
    -- Context Snapshot (JSONB)
    -- Stores specific roles/names at this moment.
    -- Ex: [{"name": "Adam", "role": "active"}, {"name": "Mom", "role": "digital_recipient"}]
    participant_context JSONB DEFAULT '[]',

    -- ==========================================
    -- 4. WHAT (The Substance)
    -- ==========================================
    -- Deterministic Categorization (For SQL Analytics)
    primary_activity TEXT,      -- e.g., "Deep Work", "Commute", "Dining"
    secondary_activities TEXT[] DEFAULT '{}', -- e.g., ["Audio Listening", "Messaging"]

    -- The "Messy" Details (JSONB)
    -- This captures the specific "Thing" done without needing 10 columns.
    -- Ex: { "app_name": "VS Code", "file": "main.rs", "video_title": "Gemini Update", "transaction_merchant": "Hattie B's" }
    activity_payload JSONB DEFAULT '{}',

    -- ==========================================
    -- 5. HOW (The Qualia/Texture)
    -- ==========================================
    -- Biometric & Environmental Snapshot
    -- Ex: { "avg_hr": 72, "max_hr": 110, "stress_detected": true, "environment_noise": "quiet" }
    biometric_context JSONB DEFAULT '{}',

    -- ==========================================
    -- 6. WHY (The Axiology)
    -- ==========================================
    -- Intent (From Calendar/Goal)
    declared_intent TEXT,       -- "Finish Beta Launch"

    -- Alignment (The Examen Output)
    is_aligned BOOLEAN,         -- True if What matched Why
    virtue_tags TEXT[] DEFAULT '{}',         -- ["Diligent", "Temperate"]
    vice_tags TEXT[] DEFAULT '{}',           -- ["Distracted", "Gluttonous"]

    -- ==========================================
    -- 7. SYNTHESIS (The Output)
    -- ==========================================
    -- The Human-Readable Story
    narrative_summary TEXT,     -- "Ate Hattie B's for lunch while researching Gemini models."

    -- ==========================================
    -- 8. PROVENANCE (The Ground Truth)
    -- ==========================================
    -- Why did we cut here?
    changepoint_drivers TEXT[] DEFAULT '{}', -- ["location_change", "app_category_shift"]
    changepoint_weight INTEGER,

    -- The "Refs" (JSONB) - The Graph Edges
    -- Maps specific source rows to this narrative.
    -- Ex: [ {"table": "social_email", "id": "...", "role": "trigger"}, {"table": "transaction", "id": "...", "role": "anchor"} ]
    evidence_refs JSONB DEFAULT '[]',

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT valid_duration CHECK (end_time >= start_time)
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_narrative_primitive_time ON data.narrative_primitive(start_time DESC);
CREATE INDEX IF NOT EXISTS idx_narrative_primitive_place ON data.narrative_primitive(place_id);
CREATE INDEX IF NOT EXISTS idx_narrative_primitive_participants ON data.narrative_primitive USING GIN(participant_ids);
CREATE INDEX IF NOT EXISTS idx_narrative_primitive_activity ON data.narrative_primitive(primary_activity);
CREATE INDEX IF NOT EXISTS idx_narrative_primitive_evidence ON data.narrative_primitive USING GIN(evidence_refs);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_narrative_primitive_updated_at ON data.narrative_primitive;
CREATE TRIGGER update_narrative_primitive_updated_at
    BEFORE UPDATE ON data.narrative_primitive
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- Comments
COMMENT ON TABLE data.narrative_primitive IS 'Fundamental "scenes" of a person''s day. Generated by changepoint detection + synthesis pipeline. Uses hybrid FK + JSONB snapshot model.';
COMMENT ON COLUMN data.narrative_primitive.place_label IS 'Snapshot of place name at this moment. Prevents time travel bugs when place entities are renamed.';
COMMENT ON COLUMN data.narrative_primitive.participant_context IS 'Snapshot of who was involved with their roles. Ex: [{"name": "Adam", "role": "active"}]';
COMMENT ON COLUMN data.narrative_primitive.activity_payload IS 'Messy details of what was done. Ex: {"app_name": "VS Code", "file": "main.rs"}';
COMMENT ON COLUMN data.narrative_primitive.evidence_refs IS 'Links to source ontology primitives. Ex: [{"table": "activity_app_usage", "id": "...", "role": "substance"}]';
