-- Migration 042: Add epigraph column to wiki_days
--
-- An epigraph is a one-line literary subtitle for the day, generated by the
-- nightly autobiography LLM alongside the diary. It sits at the top of the
-- day page (between h1 and the narrative) as a chapter-heading flourish.
--
-- Rendered in italic serif, muted color. ~5-14 words, Austen register.

ALTER TABLE wiki_days ADD COLUMN epigraph TEXT;
