// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication type required for a source
 */
export type AuthType = "oauth2" | "apikey" | "device" | "none";
