// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth configuration details for a source
 */
export type OAuthConfig = { 
/**
 * OAuth scopes required
 */
scopes: Array<string>, 
/**
 * Authorization URL pattern
 */
auth_url: string, 
/**
 * Token URL pattern
 */
token_url: string, };
