// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered stream type (e.g., "Calendar", "Gmail")
 * This defines what streams a source offers.
 * For user stream state, see api::StreamConnection.
 */
export type RegisteredStream = { 
/**
 * Stream identifier (e.g., "calendar", "gmail")
 */
name: string, 
/**
 * Human-readable display name
 */
display_name: string, 
/**
 * Description of what this stream provides
 */
description: string, 
/**
 * Database table name (e.g., "stream_google_calendar")
 */
table_name: string, 
/**
 * Target ontology tables this stream feeds into
 * e.g., ["praxis_calendar"] for Google Calendar
 * e.g., ["health_heart_rate", "health_sleep", "health_workout"] for HealthKit
 */
target_ontologies: Array<string>, 
/**
 * JSON schema for configuration (serialized as JSON)
 */
config_schema: any, 
/**
 * Example configuration
 */
config_example: any, 
/**
 * Whether this stream supports incremental sync
 */
supports_incremental: boolean, 
/**
 * Whether this stream supports full refresh
 */
supports_full_refresh: boolean, 
/**
 * Default cron schedule for this stream in 6-field format: sec min hour day month dow
 */
default_cron_schedule: string | null, };
