// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";
import type { OAuthConfig } from "./OAuthConfig";
import type { RegisteredStream } from "./RegisteredStream";

/**
 * A registered source type (e.g., "Google", "Notion")
 * This defines what sources CAN be connected.
 * For actual user connections, see api::SourceConnection.
 */
export type RegisteredSource = { 
/**
 * Unique identifier (e.g., "google", "notion", "ios")
 */
name: string, 
/**
 * Human-readable display name
 */
display_name: string, 
/**
 * Description of what this source provides
 */
description: string, 
/**
 * Authentication type required
 */
auth_type: AuthType, 
/**
 * Available streams for this source
 */
streams: Array<RegisteredStream>, 
/**
 * OAuth-specific configuration (if applicable)
 */
oauth_config: OAuthConfig | null, 
/**
 * Iconify icon name for UI display (e.g., "ri:google-fill")
 */
icon: string | null, };
