// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection status with sync statistics
 */
export type SourceConnectionStatus = { id: string, name: string, source: string, is_active: boolean, is_internal: boolean, last_sync_at: string | null, error_message: string | null, total_syncs: bigint, successful_syncs: bigint, failed_syncs: bigint, last_sync_status: string | null, last_sync_duration_ms: number | null, };
