// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's connected source instance
 * This represents an actual connected account with auth tokens.
 * For source type info, see registry::RegisteredSource.
 */
export type SourceConnection = { id: string, source: string, name: string, auth_type: string, is_active: boolean, is_internal: boolean, error_message: string | null, created_at: string, updated_at: string, last_sync_at: string | null, enabled_streams_count: bigint, total_streams_count: bigint, };
