// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's stream connection
 * Merges RegisteredStream (from registry) with user state (from DB).
 */
export type StreamConnection = { stream_name: string, display_name: string, description: string, table_name: string, is_enabled: boolean, cron_schedule: string | null, config: any, last_sync_at: string | null, supports_incremental: boolean, supports_full_refresh: boolean, config_schema: any, config_example: any, default_cron_schedule: string | null, };
