-- The machine's memory becomes visible, laned, and per-note.
--
-- The old carrier was app_assistant_profile.memory: one JSONB blob, written
-- whole-replace by update_memory (every save destroyed everything the model
-- failed to re-transcribe), injected into every prompt, and visible in NO
-- surface — a machine channel about the person that the person could not
-- read, the same disease the observed-data portrait was deleted for.
--
-- New shape per docs/narrative-identity.md ("Memory (block 5)"): one row per
-- memory, three lanes, add/revise/retire instead of whole-replace, author +
-- retirement provenance (memory poisoning via ingested content is a
-- documented attack class; "who wrote this, when, and why it left" is the
-- practiced defense), and a page the person reads and edits.
CREATE TABLE app_assistant_memories (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- facts = durable facts of their world; manner = how to speak and behave
    -- with them; practices = what they are holding to. The test for what
    -- belongs here at all vs the narrative identity: could a stranger who
    -- spent 200 hours beside them learn it? Then memory. Would being wrong
    -- about it insult rather than inconvenience? Then it may only ever
    -- arrive user-authored.
    lane          text NOT NULL CHECK (lane IN ('facts', 'manner', 'practices')),
    body          text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 500),
    author        text NOT NULL DEFAULT 'ai' CHECK (author IN ('ai', 'human')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    -- Retirement is soft and reasoned: the machine's pruning stays auditable.
    retired_at    timestamptz,
    retired_reason text CHECK ((retired_at IS NULL) = (retired_reason IS NULL))
);

CREATE INDEX idx_assistant_memories_live
    ON app_assistant_memories (lane, updated_at)
    WHERE retired_at IS NULL;

-- Fold the legacy blob in as one facts-lane note, then drop the column with
-- its writer and reader gone in the same change. `#>> '{}'` unwraps the JSON
-- string update_memory stored.
INSERT INTO app_assistant_memories (lane, body, author)
SELECT 'facts', left(btrim(memory #>> '{}'), 500), 'ai'
FROM app_assistant_profile
WHERE memory IS NOT NULL AND btrim(memory #>> '{}') <> '';

ALTER TABLE app_assistant_profile DROP COLUMN memory;
