-- ---------------------------------------------------------------------------
-- Stories foundations (V1 W1 — docs/stories-plan.md §8)
--
-- Notebooks become Stories: the hand-made contextual container (magnet or
-- folder via `auto_add_materials`), plus the evidence/corrigibility primitives
-- everything downstream writes into:
--
--   wiki_stories / wiki_story_members  renamed from app_notebooks/_items;
--                                      new story fields (origin, centroid,
--                                      significance, dormant axiology)
--   er_mentions                      the evidence layer: extracted mentions,
--                                      floating → linked/promoted/dismissed,
--                                      with reference_time (the future is a
--                                      query, not a table — no prospective tbl;
--                                      mention-level, not record-level, because
--                                      one record can reference many times)
--   er_extraction_log                  once-per-record extraction gate (this IS
--                                      the "processed" flag — data_* stays pure)
--   wiki_marginalia                    MEMORY: the margins of everything
--   dirty_at columns                   on events/days/stories: needs-attention
--                                      cache; set on new evidence, cleared on
--                                      refresh. No ops-queue table.
--
-- wiki_things is DEPRECATED (comment only; drop in a later cleanup): topics
-- are universals, things were particulars — particulars accumulate as floating
-- mentions until promotion pressure or a user creates them deliberately.
--
-- Deliberately NOT renamed yet (UI-phase, with the web app): the
-- `app_chats.notebook_id` column and the /api/notebooks routes.
-- Embeddings/centroids are BYTEA (wiki_events.embedding precedent) — sized by
-- the live embedder, no vector-column dims coupling.
-- ---------------------------------------------------------------------------

-- 1. Notebooks → Stories -----------------------------------------------------

ALTER TABLE app_notebooks      RENAME TO wiki_stories;
ALTER TABLE app_notebook_items RENAME TO wiki_story_members;

ALTER INDEX idx_app_notebooks_name       RENAME TO idx_wiki_stories_name;
ALTER INDEX idx_app_notebooks_sort       RENAME TO idx_wiki_stories_sort;
ALTER INDEX idx_notebook_items_notebook  RENAME TO idx_story_members_story;
ALTER INDEX idx_notebook_items_url       RENAME TO idx_story_members_url;

-- Story fields. `origin`/`last_edited_by` are the authority model; `centroid`
-- + `auto_add_materials` are the magnet; state/valence/direction/completable
-- ship dormant (axiology layer is designed + deferred — do not populate).
ALTER TABLE wiki_stories
    ADD COLUMN origin             TEXT NOT NULL DEFAULT 'user'
                                  CHECK (origin IN ('user', 'ai')),
    ADD COLUMN auto_add_materials BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN centroid           BYTEA,
    ADD COLUMN significance       DOUBLE PRECISION,
    ADD COLUMN pinned             BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN last_edited_by     TEXT NOT NULL DEFAULT 'human'
                                  CHECK (last_edited_by IN ('ai', 'human')),
    ADD COLUMN abstract           TEXT,
    ADD COLUMN state              TEXT NOT NULL DEFAULT 'active'
                                  CHECK (state IN ('aspiring', 'active', 'dormant', 'completed')),
    ADD COLUMN valence            TEXT
                                  CHECK (valence IN ('positive', 'negative', 'neutral')),
    ADD COLUMN direction          TEXT
                                  CHECK (direction IN ('cultivate', 'remove', 'pursue')),
    ADD COLUMN completable        BOOLEAN,
    ADD COLUMN parent_id          TEXT REFERENCES wiki_stories(id) ON DELETE SET NULL;

-- 2. Mentions: the evidence layer --------------------------------------------
-- Extraction output. A mention binds to its source RECORD (never to an event —
-- events re-segment; records are immutable). `reference_time` carries forward/
-- backward references: a record about next Saturday is delivered when that
-- window goes hot; backfill is the same scan pointed backward.

CREATE TABLE er_mentions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table          TEXT NOT NULL,
    source_id             TEXT NOT NULL,
    surface               TEXT NOT NULL,
    normalized            TEXT,
    mention_type          TEXT NOT NULL
                          CHECK (mention_type IN ('person', 'place', 'org', 'topic', 'other')),
    role                  TEXT,
    reference_time        TIMESTAMPTZ,
    reference_granularity TEXT
                          CHECK (reference_granularity IN ('exact', 'day', 'week', 'month', 'open')),
    embedding             BYTEA,
    status                TEXT NOT NULL DEFAULT 'floating'
                          CHECK (status IN ('floating', 'linked', 'dismissed', 'promoted')),
    entity_type           TEXT,
    entity_id             TEXT,
    confidence            DOUBLE PRECISION,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_er_mentions_source     ON er_mentions(source_table, source_id);
CREATE INDEX idx_er_mentions_status     ON er_mentions(status) WHERE status = 'floating';
CREATE INDEX idx_er_mentions_normalized ON er_mentions(normalized);
CREATE INDEX idx_er_mentions_entity     ON er_mentions(entity_type, entity_id)
    WHERE entity_id IS NOT NULL;
-- The future is a query: pull records referencing a window when it goes hot.
CREATE INDEX idx_er_mentions_reftime    ON er_mentions(reference_time)
    WHERE reference_time IS NOT NULL;

-- Once-per-record extraction gate: extraction must never re-bill the same
-- record on the rolling window (a row here means "ran", even with 0 mentions).
CREATE TABLE er_extraction_log (
    source_table  TEXT NOT NULL,
    source_id     TEXT NOT NULL,
    extracted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    model         TEXT,
    mention_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (source_table, source_id)
);

-- 3. Marginalia: the margins of everything (MEMORY) --------------------------
-- Append-only prose per object: AI + human memos, corrections, appraisals.
-- Read-before-write on every re-synthesis; indexed into retrieval so stale
-- prose never misleads the assistant. Settled prose only changes via the
-- period-close rule (stories-plan.md §3.6) — margins accrue automatically.

CREATE TABLE wiki_marginalia (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type TEXT NOT NULL
                 CHECK (subject_type IN ('event', 'day', 'story', 'person', 'place',
                                         'org', 'telos', 'chat', 'page')),
    subject_id   TEXT NOT NULL,
    kind         TEXT NOT NULL
                 CHECK (kind IN ('observation', 'style_note', 'correction',
                                 'appraisal', 'memo', 'provenance')),
    body         TEXT NOT NULL,
    author       TEXT NOT NULL CHECK (author IN ('ai', 'human')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_wiki_marginalia_subject
    ON wiki_marginalia(subject_type, subject_id, created_at);

-- 4. Dirty-at: the needs-attention cache --------------------------------------
-- No ops-queue table. New evidence about a settled object stamps dirty_at;
-- refresh/re-synthesis clears it. Badge counts and "which event has the most
-- pending evidence" are joins over wiki_marginalia/er_mentions since the
-- stamp. (The extraction "processed" gate is er_extraction_log above —
-- raw data_* tables carry no bookkeeping columns.)

ALTER TABLE wiki_events  ADD COLUMN dirty_at TIMESTAMPTZ;
ALTER TABLE wiki_days    ADD COLUMN dirty_at TIMESTAMPTZ;
ALTER TABLE wiki_stories ADD COLUMN dirty_at TIMESTAMPTZ;

CREATE INDEX idx_wiki_events_dirty  ON wiki_events(dirty_at)  WHERE dirty_at IS NOT NULL;
CREATE INDEX idx_wiki_days_dirty    ON wiki_days(dirty_at)    WHERE dirty_at IS NOT NULL;
CREATE INDEX idx_wiki_stories_dirty ON wiki_stories(dirty_at) WHERE dirty_at IS NOT NULL;

-- 5. wiki_things: deprecated --------------------------------------------------
-- No writes from resolution machinery; user CRUD remains until the UI phase
-- removes it. Particulars ("Biscuit", "the boat") live as floating mentions
-- until promotion; projects/hobbies are stories; concepts are topics.

COMMENT ON TABLE wiki_things IS
    'DEPRECATED (docs/stories-plan.md V1): no ER writes; superseded by wiki_stories (projects/hobbies), topic tags (concepts), and er_mentions promotion (recurring particulars). Drop in a later cleanup migration.';
