-- 0048 — `bm25_len` widens to BIGINT, to match the code that reads it.
--
-- 0030 created this column as `INT` (int4): "per-chunk token length", and a
-- single chunk's length genuinely never overflows int4. But every Rust site
-- treats it as i64 — `bm25_postings` RETURNS i64, and `bm_len`/`dropped_len`
-- are summed straight into `search_index_meta.sum_len`/`n_docs`, which are
-- BIGINT. The column was the one place the type disagreed.
--
-- The disagreement was invisible until a RE-INDEX. sqlx is lenient on the way
-- in (an i64 bind assignment-casts into an int4 column) but strict on the way
-- back out: the indexer's `SELECT bm25_len ... ` reads it as `Option<i64>`,
-- sqlx sees an int4 OID where it was promised int8, and the whole batch fails
--   `Rust type Option<i64> (as SQL type INT8) is not compatible with SQL type INT4`
-- A fresh index never notices — there is no prior row to read — so this only
-- ever surfaced on a box re-embedding an ontology it had indexed before.
--
-- Widen the column so the database agrees with the code, rather than teaching
-- five call sites to juggle i32/i64 casts around a value that is BIGINT the
-- moment it touches the corpus stats. One-time table rewrite; the column stays
-- 8 bytes forever after.
ALTER TABLE search_embeddings ALTER COLUMN bm25_len TYPE BIGINT;
