-- Entity articles: the wikipedia-style written record on each entity page.
--
-- `article` is MACHINE-written (regenerated by the entity_article applet when
-- enough new evidence accumulates) and deliberately separate from `content`
-- and `notes`, which stay user-authored. It is called an article rather than a
-- summary because it summarizes nothing — it is the page's prose, written from
-- the records, and the records themselves are rendered separately beneath it.
--
-- The two gating columns record what the evidence looked like at the last
-- write, so the applet can gate on growth ("enough new data") instead of a
-- timer:
--   article_updated_at — when the article was last written
--   article_ref_count  — how many wiki_entity_refs the entity had at that time

ALTER TABLE wiki_people
    ADD COLUMN article TEXT,
    ADD COLUMN article_updated_at TIMESTAMPTZ,
    ADD COLUMN article_ref_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE wiki_places
    ADD COLUMN article TEXT,
    ADD COLUMN article_updated_at TIMESTAMPTZ,
    ADD COLUMN article_ref_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE wiki_orgs
    ADD COLUMN article TEXT,
    ADD COLUMN article_updated_at TIMESTAMPTZ,
    ADD COLUMN article_ref_count INTEGER NOT NULL DEFAULT 0;
