-- Entity summaries: the wikipedia-style written record on each entity page.
--
-- `summary` is MACHINE-written (regenerated by the entity_summary applet when
-- enough new evidence accumulates) and deliberately separate from `content`
-- and `notes`, which stay user-authored. The two gating columns record what
-- the record looked like at the last write, so the applet can gate on growth
-- ("enough new data") instead of a timer:
--   summarized_at     — when the summary was last generated
--   summary_ref_count — how many wiki_entity_refs the entity had at that time

ALTER TABLE wiki_people
    ADD COLUMN summary TEXT,
    ADD COLUMN summarized_at TIMESTAMPTZ,
    ADD COLUMN summary_ref_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE wiki_places
    ADD COLUMN summary TEXT,
    ADD COLUMN summarized_at TIMESTAMPTZ,
    ADD COLUMN summary_ref_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE wiki_orgs
    ADD COLUMN summary TEXT,
    ADD COLUMN summarized_at TIMESTAMPTZ,
    ADD COLUMN summary_ref_count INTEGER NOT NULL DEFAULT 0;
