-- 0078 — Drop `app_link_session`.
--
-- Created by 0026 and never used. No Rust references it — not a query, not a
-- struct, not a migration since its own — and it holds zero rows. It survived
-- the pairing rewrite that made it redundant (pairing is local-first now: the
-- box prints a code, the device presents it, and the fanout is served from
-- `app_device` + the applet rows).
--
-- Found while renaming actions→applets, because its `action_ids` column looked
-- like the wire contract the macOS collector reads. It is not: that key comes
-- from `ConsumeResponse.action_ids`, a struct field. Migrations 0076 and 0077
-- both say otherwise in their comments — they are wrong, and they stay wrong,
-- because sqlx checksums applied migrations and editing one to correct prose
-- would break `migrate run` on every box that already has it. This is the
-- correction, in the only place a correction can safely live.
--
-- Dropped rather than left: an unused table with a plausible name is worse
-- than no table. It cost one wrong assumption in this rename already, and the
-- next person to grep for `action_ids` would find it first.

DROP TABLE IF EXISTS app_link_session;
