-- ---------------------------------------------------------------------------
-- Drop two tables nothing creates rows in and nothing reads.
--
-- Found by cross-referencing every table in the schema against the codebase and
-- against live row counts on a real box (2026-08-17):
--
--   app_namespaces          a multi-tenancy seam from before the box was
--                           understood to be single-tenant by construction.
--                           `docs/auth-model.md`: the owner IS the tenant, and
--                           an appliance has no second one to separate from.
--
--   elt_stream_checkpoints  from the ELT-era source model, replaced by "a source
--                           is a credential plus an applet on a schedule"
--                           (`credentials`, `app_applets`, `app_applet_runs`).
--                           Nothing has written a checkpoint since.
--
-- Both are empty on the only box that exists, referenced nowhere in the code,
-- and — the check that matters — have no database objects depending on them.
--
-- ## What was in this migration and is not
--
-- `elt_source_connections`, the third member of the dead `elt_` family, was
-- here until it refused to drop:
--
--     cannot drop table elt_source_connections because other objects depend on it
--
-- It has zero rows and zero code references, and it is still load-bearing:
-- TWENTY-ONE `data_*` tables carry a `source_connection_id` foreign key to it.
-- Two measures of deadness were not enough, and the third — asking the database
-- what depends on it — is the one that would have been skipped by anyone
-- reasoning from grep alone. Recorded here because the next person to look at
-- `elt_source_connections` will reach the same wrong conclusion I did.
--
-- The column is genuinely vestigial: on the live box `source_connection_id` is
-- NULL for 100% of rows in every table that has it (112,104 location points,
-- 27,283 heart-rate samples, and so on). So the cleanup is real — 21 dead
-- columns and 21 dead constraints — but it is a schema change across a third of
-- the data model, not a line in a tidy-up migration, and it deserves its own
-- change with its own reasoning. Left alone deliberately.
--
-- Narrow on purpose. A deletion is the one change that cannot be reviewed after
-- the fact, so this takes only what three independent checks agree is dead and
-- leaves everything merely suspicious standing. The six tables outside the five
-- prefix families (`credentials`, `box_secrets`, `backup_archived_file`,
-- `lake_objects`, `storage_volume`, `extracted_document_chunks`) are all live;
-- renaming them is separate and reversible.
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS elt_stream_checkpoints;
DROP TABLE IF EXISTS app_namespaces;
