/**
 * Thinking labels for the animated thinking indicator.
 *
 * Inspired by Claude Code's whimsical loading states.
 * Full list of 90+ creative verbs that convey cognitive processing.
 */

export const THINKING_LABELS = [
	'Accomplishing',
	'Actioning',
	'Alchemizing',
	'Actualizing',
	'Baking',
	'Booping',
	'Brewing',
	'Calibrating',
	'Calculating',
	'Cerebrating',
	'Channelling',
	'Churning',
	'Clauding',
	'Coalescing',
	'Cogitating',
	'Combobulating',
	'Computing',
	'Concocting',
	'Conjuring',
	'Considering',
	'Contemplating',
	'Cooking',
	'Crafting',
	'Creating',
	'Crystallizing',
	'Crunching',
	'Daydreaming',
	'Deciphering',
	'Deliberating',
	'Determining',
	'Discerning',
	'Discombobulating',
	'Distilling',
	'Divining',
	'Doing',
	'Effecting',
	'Elucidating',
	'Enchanting',
	'Envisioning',
	'Extrapolating',
	'Finagling',
	'Flibbertigibbeting',
	'Forging',
	'Forming',
	'Frolicking',
	'Gallivanting',
	'Generating',
	'Germinating',
	'Hatching',
	'Herding',
	'Honking',
	'Hustling',
	'Hypothesizing',
	'Ideating',
	'Imagining',
	'Incubating',
	'Inferring',
	'Jiving',
	'Manifesting',
	'Marinating',
	'Meandering',
	'Moseying',
	'Mulling',
	'Mustering',
	'Musing',
	'Noodling',
	'Percolating',
	'Perusing',
	'Philosophising',
	'Pondering',
	'Pontificating',
	'Processing',
	'Puttering',
	'Puzzling',
	'Reticulating',
	'Ruminating',
	'Scheming',
	'Schlepping',
	'Shimmying',
	'Shucking',
	'Simmering',
	'Smooshing',
	'Spelunking',
	'Spinning',
	'Stewing',
	'Sussing',
	'Synthesizing',
	'Thinking',
	'Tinkering',
	'Transmuting',
	'Unfurling',
	'Untangling',
	'Unravelling',
	'Vibing',
	'Virtuing',
	'Wandering',
	'Whirring',
	'Wibbling',
	'Wizarding',
	'Working',
	'Wrangling'
] as const;

/**
 * Returns a random thinking label from the full list.
 *
 * No filtering by intent type - keeps the experience fun and unpredictable.
 */
export function getRandomThinkingLabel(): string {
	const randomIndex = Math.floor(Math.random() * THINKING_LABELS.length);
	return THINKING_LABELS[randomIndex];
}
