//! Build-time lockstep for the plugins under `apps/web/plugins/`.
//!
//! A Tauri plugin command must appear in four places: `build.rs` COMMANDS
//! (drives ACL codegen — a command missing here is refused at runtime no
//! matter what the permission TOMLs say), `lib.rs`'s `generate_handler!`,
//! `permissions/default.toml`, and `permissions/autogenerated/`. Hand-syncing
//! them has failed three times — the `provision_*` trio (2026-08-10),
//! `improv_pair_code` (2026-08-19), `audio.set_notify` (2026-08-26) — and each
//! time the failure was a silent runtime ACL refusal on a real device, because
//! a stale permission TOML satisfies every build-time reference while the
//! runtime refuses the command.
//!
//! So COMMANDS becomes the single source of truth. Each plugin's `build.rs`
//! calls [`enforce`] before `tauri_plugin::Builder`, which:
//!   1. diffs COMMANDS against `generate_handler!` in `src/lib.rs` and fails
//!      the build, both directions, naming the drifted command;
//!   2. deletes stale `permissions/autogenerated/commands/*.toml` for commands
//!      COMMANDS no longer knows (the masking artifact);
//!   3. generates `permissions/default.toml` from COMMANDS — every plugin's
//!      default set is a plain allow-everything list, pure transcription, and
//!      transcription errors were the whole disease;
//!   4. diffs the plugin's own `guest-js/` wrappers against COMMANDS — the
//!      same drift arriving from the JS side.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

/// Enforce lockstep with every command in the default permission set.
pub fn enforce(commands: &[&str]) {
    enforce_excluding(commands, &[]);
}

/// Like [`enforce`], but keeps `excluded_from_default` out of the generated
/// default permission set (for a future command that should be opted into by a
/// capability explicitly). Excluded commands are still verified against
/// `generate_handler!` and still keep their autogenerated permission files.
pub fn enforce_excluding(commands: &[&str], excluded_from_default: &[&str]) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let plugin = env::var("CARGO_PKG_NAME")
        .expect("CARGO_PKG_NAME")
        .trim_start_matches("tauri-plugin-")
        .to_string();
    let root = Path::new(&manifest_dir);

    for cmd in excluded_from_default {
        assert!(
            commands.contains(cmd),
            "[{plugin}] `{cmd}` is excluded from the default permission set but is not in COMMANDS"
        );
    }

    check_handlers(root, &plugin, commands);
    check_guest_js(root, &plugin, commands);
    prune_stale_permissions(root, &plugin, commands);
    write_default_toml(root, &plugin, commands, excluded_from_default);
}

/// Diff COMMANDS against the union of every `generate_handler![...]` block in
/// `src/lib.rs`. Registered-but-unlisted commands are the historical bug (ACL
/// refuses them at runtime); listed-but-unregistered would grant a permission
/// for a command that errors on dispatch — both fail the build.
fn check_handlers(root: &Path, plugin: &str, commands: &[&str]) {
    let lib_path = root.join("src/lib.rs");
    println!("cargo:rerun-if-changed={}", lib_path.display());
    let lib = fs::read_to_string(&lib_path)
        .unwrap_or_else(|e| panic!("[{plugin}] cannot read {}: {e}", lib_path.display()));

    let mut registered = BTreeSet::new();
    let mut rest = lib.as_str();
    while let Some(at) = rest.find("generate_handler!") {
        rest = &rest[at + "generate_handler!".len()..];
        let open = rest.find('[').unwrap_or_else(|| {
            panic!("[{plugin}] generate_handler! without a `[` in src/lib.rs")
        });
        let close = rest[open..].find(']').unwrap_or_else(|| {
            panic!("[{plugin}] generate_handler! without a `]` in src/lib.rs")
        });
        for line in rest[open + 1..open + close].lines() {
            let line = line.split("//").next().unwrap_or("");
            for entry in line.split(',') {
                let name = entry.trim().rsplit("::").next().unwrap_or("").trim();
                if !name.is_empty() {
                    registered.insert(name.to_string());
                }
            }
        }
        rest = &rest[open + close..];
    }
    assert!(
        !registered.is_empty(),
        "[{plugin}] no generate_handler! block found in src/lib.rs"
    );

    let listed: BTreeSet<String> = commands.iter().map(|c| c.to_string()).collect();
    let unlisted: Vec<_> = registered.difference(&listed).collect();
    let unregistered: Vec<_> = listed.difference(&registered).collect();
    assert!(
        unlisted.is_empty() && unregistered.is_empty(),
        "[{plugin}] COMMANDS in build.rs and generate_handler! in src/lib.rs have drifted.\n\
         registered in lib.rs but missing from COMMANDS (the ACL would refuse these at runtime): {unlisted:?}\n\
         in COMMANDS but not registered in lib.rs (permission granted for a command that cannot dispatch): {unregistered:?}"
    );
}

/// Diff the plugin's own `guest-js/` wrappers against COMMANDS. A wrapper that
/// invokes `plugin:<name>|<cmd>` for a command COMMANDS no longer knows is this
/// same drift arriving from the JS side, and it fails identically: the ACL has
/// nothing to resolve, so the first caller to reach for the wrapper gets
/// "not allowed by ACL" rather than anything naming the deleted command.
/// `improv_link_code`/`improv_pair_code` outlived their Rust commands that way
/// — deleted 2026-08-24, wrappers still exported and found by hand on
/// 2026-08-28. Only latent, because nothing had called them yet.
///
/// Scoped to this plugin's `guest-js/`, which is the part of the JS side a
/// plugin build script owns. Callers elsewhere in the web app invoke by raw
/// string and are out of reach from here.
///
/// One direction only: a command with no wrapper is ordinary (iOS-only
/// commands, and commands `src/` invokes by string, both have none).
fn check_guest_js(root: &Path, plugin: &str, commands: &[&str]) {
    let dir = root.join("guest-js");
    let Ok(entries) = fs::read_dir(&dir) else { return };
    println!("cargo:rerun-if-changed={}", dir.display());

    let needle = format!("plugin:{plugin}|");
    let mut stale: BTreeSet<String> = BTreeSet::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().map(|e| e != "ts").unwrap_or(true) {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let src = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("[{plugin}] cannot read {}: {e}", path.display()));
        let mut rest = src.as_str();
        while let Some(at) = rest.find(&needle) {
            rest = &rest[at + needle.len()..];
            let name: String = rest
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() && !commands.contains(&name.as_str()) {
                stale.insert(name);
            }
        }
    }

    assert!(
        stale.is_empty(),
        "[{plugin}] guest-js invokes commands that are not in COMMANDS \
         (the ACL would refuse these at runtime): {stale:?}\n\
         Either add them to COMMANDS and register them in src/lib.rs, or delete \
         the wrappers — a wrapper for a deleted command is a trap for its next caller."
    );
}

/// Delete autogenerated permission TOMLs for commands that no longer exist.
/// A stray file here is what let `audio.set_notify` reference a permission at
/// build time while the runtime ACL refused the command.
fn prune_stale_permissions(root: &Path, plugin: &str, commands: &[&str]) {
    let dir = root.join("permissions/autogenerated/commands");
    let Ok(entries) = fs::read_dir(&dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().map(|e| e != "toml").unwrap_or(true) {
            continue;
        }
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        if !commands.contains(&stem) {
            fs::remove_file(&path)
                .unwrap_or_else(|e| panic!("[{plugin}] cannot prune {}: {e}", path.display()));
            println!(
                "cargo:warning=[{plugin}] pruned stale permission {} — no such command in COMMANDS",
                path.display()
            );
        }
    }
}

/// Generate `permissions/default.toml` from COMMANDS. Written only when the
/// content differs, so an in-lockstep build touches nothing.
fn write_default_toml(root: &Path, plugin: &str, commands: &[&str], excluded: &[&str]) {
    let perms: Vec<String> = commands
        .iter()
        .filter(|c| !excluded.contains(c))
        .map(|c| format!("\"allow-{}\"", c.replace('_', "-")))
        .collect();
    let content = format!(
        "# Generated by virtues-plugin-lockstep from COMMANDS in build.rs — do not edit.\n\
         [default]\n\
         description = \"Default permissions for the {plugin} plugin\"\n\
         permissions = [{}]\n",
        perms.join(", ")
    );
    let path = root.join("permissions/default.toml");
    if fs::read_to_string(&path).ok().as_deref() != Some(content.as_str()) {
        fs::write(&path, content)
            .unwrap_or_else(|e| panic!("[{plugin}] cannot write {}: {e}", path.display()));
    }
}
