-- Diagnostic beacons from Virtues boxes.
--
-- Two event types today:
--   - 'install': posted by scripts/install.sh at the end of an install
--     attempt (success or failure). Carries distro, version, arch,
--     outcome, and the failed step name when not OK.
--   - 'crash': posted by virtues-core's `report-crash` CLI (wired into
--     systemd's ExecStopPost). Carries exit code, service result, and the
--     last 50 journal lines.
--
-- No customer/email/identity column. `box_id` is a per-install opaque
-- hash (machine-id or hostname → SHA-256 prefix); it's enough to dedupe
-- retries from the same box, not enough to identify a person. The whole
-- payload (everything beyond the typed columns) lives in `payload` JSONB.
--
-- Append-only. Reaped by a daily cron after 90 days.

CREATE TABLE diag_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    box_id      TEXT NOT NULL,
    event_type  TEXT NOT NULL CHECK (event_type IN ('install', 'crash')),
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    src_ip      TEXT
);

CREATE INDEX idx_diag_events_received  ON diag_events (received_at DESC);
CREATE INDEX idx_diag_events_box       ON diag_events (box_id, received_at DESC);
CREATE INDEX idx_diag_events_type_box  ON diag_events (event_type, box_id, received_at DESC);
