#!/usr/bin/env python3
"""Check README.md — the four invariants its serif headings quietly created.

WHY THIS EXISTS

The README does not render its headings as text. Each one is a theme-aware SVG
pair generated by `.github/images/headings/gen.py`, wrapped in a <picture>, with
a hand-written `<a id>` above it because GitHub cannot anchor an image, and a
hand-written table of contents because the Outline sidebar shows blank labels.
That is four coupled things per heading, all maintained by hand, and nothing
checked any of them.

Every rule below is a failure that actually happened while the file was being
rewritten on 2026-09-03, and every one of them reached a push:

  1. A line inside the heading-convention comment quoted `-->`. An HTML comment
     ends at the FIRST terminator it contains, so five lines of authoring notes
     and a stray arrow rendered above the cover image for everyone.
  2. The three badges lost their `![...]` wrappers somewhere in an edit and
     became plain links. Still valid markdown; simply no badges.
  3. Renaming sections left forty orphaned SVG pairs, and one <picture> kept
     pointing at a file that had been deleted.
  4. A renamed heading left its TOC entry pointing at an anchor nobody defined.

None of these break a build, which is why they survive review: the file renders,
just wrongly. This is the closest thing to a compiler the file can have.

Usage: tools/check-readme.py [readme_path]
"""

import re
import sys
from pathlib import Path

HEADINGS_DIR = Path(".github/images/headings")
# The example filenames inside the convention comment, which name no real file.
EXAMPLE_SVGS = {"h2-foo-dark.svg", "h2-foo-light.svg"}
MIN_ALT = 40

errors: list[str] = []


def error(msg: str) -> None:
    errors.append(msg)


def gen_slug(text: str) -> str:
    """gen.py's filename slug. Must stay in step with it."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def blank_fences_and_comments(text: str) -> str:
    """Blank fenced code and HTML comments, keeping line numbers intact.

    A shell comment inside a ```bash fence starts with '#' and is not a heading;
    the example <picture> inside the convention comment names no real file.
    Checking either produces a failure that cannot be fixed."""
    out, in_fence = [], False
    for line in text.split("\n"):
        if re.match(r"^\s*```", line):
            in_fence = not in_fence
            out.append("")
            continue
        out.append("" if in_fence else line)
    blanked = "\n".join(out)
    # Comments span lines; replace each with the same number of newlines.
    return re.sub(r"<!--.*?-->", lambda m: "\n" * m.group(0).count("\n"), blanked, flags=re.S)


def check_comments(text: str) -> None:
    """A comment ends at its FIRST `-->`, including one you only meant to quote.

    The tell is not a terminator inside the body — a non-greedy match already
    ends there, so the body looks clean. It is the terminator left STRANDED in
    ordinary text afterwards: the one the author believed was closing the block.
    Walk the document the way a parser does and report any `-->` reached while
    no comment is open.
    """
    pos = 0
    while True:
        opener = text.find("<!--", pos)
        closer = text.find("-->", pos)
        if closer == -1:
            if opener != -1:
                line = text[:opener].count("\n") + 1
                error(f"line {line}: <!-- is never terminated")
            return
        if opener == -1 or closer < opener:
            line = text[:closer].count("\n") + 1
            error(f"line {line}: a stray '-->' outside any comment — an earlier block "
                  f"closed at a terminator it only meant to quote, and everything "
                  f"between renders as visible text")
            pos = closer + 3
            continue
        close = text.find("-->", opener + 4)
        if close == -1:
            line = text[:opener].count("\n") + 1
            error(f"line {line}: <!-- is never terminated")
            return
        pos = close + 3


def check_headings(text: str, lines: list[str]) -> set[str]:
    """Every heading is a <picture> whose two SVGs exist and whose filename
    still matches the heading it claims to show."""
    referenced: set[str] = set()
    pattern = re.compile(
        r'^(#{1,3}) <picture><source media="\(prefers-color-scheme: dark\)" '
        r'srcset="([^"]+)"><img alt="([^"]+)" src="([^"]+)" height="(\d+)"></picture>$')

    for i, line in enumerate(lines, 1):
        if not re.match(r"^#{1,3} ", line):
            continue
        m = pattern.match(line)
        if not m:
            error(f"line {i}: heading is not the <picture> + SVG pattern — see the "
                  f"convention block at the top of the file")
            continue
        level, dark, alt, light, _height = m.groups()
        for src in (dark, light):
            referenced.add(Path(src).name)
            if not Path(src).exists():
                error(f"line {i}: heading image {src} does not exist — run "
                      f"python3 {HEADINGS_DIR}/gen.py")
        # A renamed heading whose SVG was never regenerated still renders, showing
        # the OLD words. The filename encodes the text, so it can be checked.
        want = f"h{len(level)}-{gen_slug(alt)}"
        if Path(light).stem != f"{want}-light":
            error(f"line {i}: heading says {alt!r} but its image is "
                  f"{Path(light).name} — expected {want}-light.svg. Add the heading "
                  f"to gen.py, re-run it, and update both filenames.")
        # H2/H3 need an anchor: GitHub cannot generate one for an image.
        if len(level) >= 2:
            above = "\n".join(lines[max(0, i - 4):i - 1])
            if '<a id="' not in above:
                error(f"line {i}: heading {alt!r} has no <a id> above it, so nothing "
                      f"can link to it")
    return referenced


def check_anchors(text: str) -> None:
    ids = set(re.findall(r'<a id="([^"]+)"></a>', text))
    for target in set(re.findall(r"\]\(#([^)]+)\)", text)):
        if target not in ids:
            error(f"link to #{target} resolves to no <a id> in the file")


def check_images(text: str) -> None:
    for m in re.finditer(r"<img\s[^>]*>", text):
        tag = m.group(0)
        src = re.search(r'src="([^"]+)"', tag)
        alt = re.search(r'alt="([^"]*)"', tag)
        if not src:
            error(f"an <img> has no src: {tag[:60]}…")
            continue
        if not src.group(1).startswith("http") and not Path(src.group(1)).exists():
            error(f"image {src.group(1)} does not exist")
        if "/headings/" in src.group(1):
            continue  # heading alt is the heading text, checked above
        if not alt or len(alt.group(1)) < MIN_ALT:
            error(f"image {src.group(1)} needs alt text describing what is in frame "
                  f"(at least {MIN_ALT} characters)")
        elif re.match(r"\s*(a )?(screenshot|image|picture)\b", alt.group(1), re.I):
            error(f"image {src.group(1)}: alt text describes the medium, not the "
                  f"content — say what is in the frame")


def check_badges(text: str) -> None:
    """A badge that loses its `![...]` wrapper is still a valid link, and simply
    stops being a badge."""
    # Collect the URLs that ARE images first: a badge is written
    # [![alt](badge)](target), and a naive scan reads that outer bracket pair as
    # a plain link to the badge.
    as_image = set(re.findall(r"!\[[^\]]*\]\(([^)]+)\)", text))
    for url in set(re.findall(r"\]\(([^)]+)\)", text)):
        looks_like_badge = "img.shields.io" in url or url.endswith("badge.svg")
        if looks_like_badge and url not in as_image:
            error(f"badge {url} is a plain link, not an image — it needs the "
                  f"[![alt](badge)](target) form")


def check_local_links(text: str) -> None:
    for target in set(re.findall(r"\]\((?!https?:|#)([^)\s]+)\)", text)):
        path = target.split("#")[0]
        if path and not Path(path).exists():
            error(f"link to {target} points at a path that does not exist")


def check_orphans(referenced: set[str]) -> None:
    if not HEADINGS_DIR.is_dir():
        return
    for svg in sorted(HEADINGS_DIR.glob("*.svg")):
        if svg.name not in referenced and svg.name not in EXAMPLE_SVGS:
            error(f"{svg} is referenced by nothing — delete it, or the next reader "
                  f"assumes it is in use")


def main() -> int:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "README.md")
    if not path.exists():
        print(f"check-readme: no README at {path}", file=sys.stderr)
        return 2
    text = path.read_text()
    check_comments(text)                 # on the raw text: nesting is the bug
    body = blank_fences_and_comments(text)
    lines = body.split("\n")

    referenced = check_headings(body, lines)
    check_anchors(body)
    check_images(body)
    check_badges(body)
    check_local_links(body)
    check_orphans(referenced)

    if errors:
        print(f"check-readme: {len(errors)} problem(s)\n", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 1

    headings = len([l for l in lines if re.match(r"^#{1,3} ", l)])
    images = len(re.findall(r"<img\s", body)) - headings
    print(f"check-readme: ok — {headings} headings, {images} images, "
          f"{len(referenced)} heading SVGs, no orphans")
    return 0


if __name__ == "__main__":
    sys.exit(main())
