#!/usr/bin/env bash
#
# stamp-mac-version.sh — generate apps/mac-source/Sources/Version.swift.
#
# The collector is a separate binary from the app that ships it, so it can only
# know its own release if something writes it in. It used to be a literal —
# `current = "1.0.0"`, `gitCommit = "unknown" // Will be set during CI build` —
# and release-mac.yml did set it, with an inline `sed`. Locally nothing did.
#
# That divergence is the bug this script exists to remove. `make mac-app`
# produced a collector that reported 1.0.0 forever, so Settings → This Mac
# showed "behind the app — relaunch Virtues" permanently: the app said 1.0.25,
# the collector said 1.0.0, and no amount of relaunching could make those two
# agree, because the number was never about what was installed. A warning that
# cannot be cleared teaches people to ignore the warning.
#
# One generator, called by BOTH paths (tools/build-mac-app.sh and
# .github/workflows/release-mac.yml), so they cannot drift again.
#
# Written WHOLESALE rather than patched in place, deliberately. The old `sed`
# matched `gitCommit = "unknown"` literally, so a second run over an
# already-stamped file left the previous commit sitting there looking current —
# fine on a throwaway runner that always starts from a clean checkout, a trap
# on any machine that builds twice.
#
# The file is generated and gitignored, like the xcframework beside it. It must
# not be tracked: stamping a tracked file dirties a checkout that several agents
# share, and the next `git add` sweeps a build artifact into someone's commit.
#
#   Usage:  tools/stamp-mac-version.sh [version]
#           (version defaults to .version in apps/web/src-tauri/tauri.conf.json —
#            the app's own version, which is the number the collector is
#            compared against)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/apps/mac-source/Sources/Version.swift"
TAURI_CONF="$REPO_ROOT/apps/web/src-tauri/tauri.conf.json"

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  VERSION="$(jq -r '.version // empty' "$TAURI_CONF")"
fi
# An empty version is worse than a wrong one: it ships a collector that reports
# nothing and compares unequal to everything, which is the failure we are here
# to remove. Refuse instead.
if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
  echo "error: no version — pass one, or fix .version in $TAURI_CONF" >&2
  exit 1
fi

# `git rev-parse` fails outside a work tree (a source tarball); "unknown" is the
# honest answer there and is what `clientHeader` already renders as "dev".
SHA="$(git -C "$REPO_ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo unknown)"
DATE="$(date -u +%Y-%m-%d)"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<SWIFT
// GENERATED by tools/stamp-mac-version.sh — do not edit, do not commit.
// Every build regenerates it; see that script for why this is not a literal.
struct Version {
    static let current = "$VERSION"
    static let buildDate = "$DATE"
    static let gitCommit = "$SHA"

    static var full: String {
        return "\\(current) (\\(buildDate))"
    }

    static var userAgent: String {
        return "virtues-mac/\\(current)"
    }

    /// \`X-Virtues-Client\` value for every request to the box. For a collector,
    /// \`version\` IS the binary's release (there is no separate UI bundle), so
    /// the box's Devices page finally gets to say what build this daemon is —
    /// it read "version unknown" forever because this identity was transmitted
    /// to nobody.
    static var clientHeader: String {
        let sha = gitCommit == "unknown" ? "dev" : String(gitCommit.prefix(7))
        return "version=\\(current); sha=\\(sha)"
    }
}
SWIFT

echo "✓ stamped collector $VERSION ($SHA, $DATE) → ${OUT#"$REPO_ROOT"/}"
